export const API_PREFIX = "/api";

export const API = {
  health: `${API_PREFIX}/health`,
  vendors: `${API_PREFIX}/vendors`,
  billing: `${API_PREFIX}/vendors`,
  companies: `${API_PREFIX}/companies`,
  agents: `${API_PREFIX}/agents`,
  projects: `${API_PREFIX}/projects`,
  issues: `${API_PREFIX}/issues`,
  goals: `${API_PREFIX}/goals`,
  approvals: `${API_PREFIX}/approvals`,
  plans: `${API_PREFIX}/companies`,
  secrets: `${API_PREFIX}/secrets`,
  costs: `${API_PREFIX}/costs`,
  activity: `${API_PREFIX}/activity`,
  dashboard: `${API_PREFIX}/dashboard`,
  sidebarBadges: `${API_PREFIX}/sidebar-badges`,
  invites: `${API_PREFIX}/invites`,
  joinRequests: `${API_PREFIX}/join-requests`,
  members: `${API_PREFIX}/members`,
  templates: `${API_PREFIX}/templates`,
  integrations: `${API_PREFIX}/integrations`,
  admin: `${API_PREFIX}/admin`,
} as const;
